### ISSUE TITLE
BSaber playlist one click install not working

### ISSUE THREAD

**Issue by chpoit** [bsmg/ModAssistant#126]
I don't know if it's normal, an issue with modassistant, or an issue with BSaber, but I can't get the one-click install for playlists to work.

Songs use this type of link: `beatsaver://9ccc`

Playlists use this type of link: `modsaber://playlist/https://bsaber.com/PlaylistAPI/Best-KPop-Maps-Vol-5_bloodcloak.bplist`

I tried swapping the `modsaber` for `beatsaver`, but I get an error. 

Are playlists supported?

**Comment by Assistant** [comment]
Playlist support doesn't exist currently. That might change in the future.
