### ISSUE TITLE
Feature Request: Option to do OneClick installs in the background again

### ISSUE THREAD

**Issue by milovincent** [bsmg/ModAssistant#171]
I'm using a python script that opens beatsaver:// URLs and until now, it worked fine, but come the latest update, hundreds of windows open for OneClick installs, and stay open. I'd like to be able to change that.

**Comment by Sunchester** [comment]
I would also like this feature to disable the OneClick GUI.

**Comment by DingusPingus** [comment]
at least make the installing happen on one window, rather then opening a new one every single time you install a song.

**Comment by milovincent** [comment]
> I would also like this feature to disable the OneClick GUI.
that's what running in the background generally entails

**Comment by deinlandel** [comment]
I vote for this also. After installing 20 songs you have 20 open windows and after each one click install click the focus is stolen from the browser. This is incredibly frustrating

**Comment by milovincent** [comment]
ftr this isn't hard to do if you download the solution and delete a few lines

**Comment by ModdingPink** [comment]
Stale
