### ISSUE TITLE
Some Mods Install, but NONE show in game

### ISSUE THREAD

**Issue by Gladddly** [bsmg/ModAssistant#197]
I am left with this error message every time. I think it may have to do with the fact that i previously downloaded Beat Saber on a internal harddrive that was not the C;/ hard drive. it was D:/ (Data, 2TB)
![bug](https://user-images.githubusercontent.com/66861326/84561513-19fdb100-ad1b-11ea-8cd0-a515932bc185.png)

**Comment by tkin1235** [comment]
I have this exact same issue/situation.

**Comment by ModdingPink** [comment]
Stale, will review if this issue occurs again on new versions
