### ISSUE TITLE
How To Install.

### ISSUE THREAD

**Issue by willliid** [bsmg/ModAssistant#417]
Need to know how to install, i installed the .exe file but when i run it it asks me to manually find my 'beat saber install folder'

**Comment by MuminKhan** [comment]
1. Make sure BeatSaber is installed 
2. Run the game at least once
3. Look for BeatSaber in the following locations: 
    * C:\Program Files\Oculus\Software\Software\hyperbolic-magnetism-beat-saber
    * C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\
    * [YOUR CUSTOM STEAM LIBRARY PATH]\steamapps\common\Beat Saber\
4. Browse to the location in ModAssistant
