### ISSUE TITLE
Mods not installing to the plugins folder

### ISSUE THREAD

**Issue by RealMrCactus** [bsmg/ModAssistant#451]
Literally will not install the the plugins folder i have the right path selected and everything im not sure where the installs go

**Comment by Melopod** [comment]
Have you tried running the game?

**Comment by gregcline** [comment]
I'm experiencing something similar. Tried uninstalling Beat Saber and downgrading, running once, then redoing my mods from a smaller set and running a second time. I can see the plugin files in `IPA/Pending`, but they don't seem to get moved over to `Beat Saber/Plugins`.

I noticed a `System.IO.IOException` in the logs, not sure if it's related though. I'm running version 1.1.26 of ModAssistant and version 1.18.3 of Beat Saber.

Thanks for all the work on this by the way, makes Beat Saber a joy.

<details>
<summary>Log</summary>
<pre>
[DEBUG @ 10:48:06 | IPA/LibraryLoader] Resolving library 0Harmony, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null
[DEBUG @ 10:48:06 | IPA] Initializing logger
[DEBUG @ 10:48:06 | IPA/LibraryLoader] Looking for file 0Harmony.dll
[DEBUG @ 10:48:06 | IPA/LibraryLoader] Found file 0Harmony.dll as C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Libs\0Harmony.dll
[DEBUG @ 10:48:06 | IPA/LibraryLoader] Resolving library Hive.Versioning, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null
[DEBUG @ 10:48:06 | IPA/LibraryLoader] Looking for file Hive.Versioning.dll
[DEBUG @ 10:48:06 | IPA/LibraryLoader] Found file Hive.Versioning.dll as C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Libs\Hive.Versioning.dll
[DEBUG @ 10:48:06 | IPA/LibraryLoader] Resolving library SemVer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[DEBUG @ 10:48:06 | IPA/LibraryLoader] Looking for file SemVer.dll
[DEBUG @ 10:48:06 | IPA/LibraryLoader] Found file SemVer.dll as C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Libs\SemVer.dll
[DEBUG @ 10:48:06 | IPA/LibraryLoader] Resolving library MonoMod.RuntimeDetour, Version=21.4.21.3, Culture=neutral, PublicKeyToken=null
[DEBUG @ 10:48:06 | IPA/LibraryLoader] Looking for file MonoMod.RuntimeDetour.dll
[DEBUG @ 10:48:06 | IPA/LibraryLoader] Found file MonoMod.RuntimeDetour.dll as C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Libs\MonoMod.RuntimeDetour.dll
[DEBUG @ 10:48:06 | IPA/LibraryLoader] Resolving library MonoMod.Utils, Version=21.7.8.3, Culture=neutral, PublicKeyToken=null
[DEBUG @ 10:48:06 | IPA/LibraryLoader] Looking for file MonoMod.Utils.dll
[DEBUG @ 10:48:06 | IPA/LibraryLoader] Found file MonoMod.Utils.dll as C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Libs\MonoMod.Utils.dll
[DEBUG @ 10:48:07 | IPA/Config] Generated impl ReadFrom IPA.Config.SelfConfig<Generated>
[NOTICE @ 10:48:07 | IPA/Config] Attempting to deserialize null
[DEBUG @ 10:48:07 | IPA] SelfConfig Changed called
[DEBUG @ 10:48:07 | IPA/Config] Generated impl WriteTo IPA.Config.SelfConfig<Generated>
[DEBUG @ 10:48:07 | IPA/Config] Generated impl ReadFrom IPA.Loader.DisabledConfig<Generated>
[NOTICE @ 10:48:07 | IPA/Config] Attempting to deserialize null
[DEBUG @ 10:48:07 | IPA/LibraryLoader] Resolving library Mono.Cecil, Version=0.11.4.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[DEBUG @ 10:48:07 | IPA/LibraryLoader] Looking for file Mono.Cecil.dll
[DEBUG @ 10:48:07 | IPA/LibraryLoader] Found file Mono.Cecil.dll as C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Libs\Mono.Cecil.dll
[DEBUG @ 10:48:07 | IPA/LibraryLoader] Resolving library Mono.Cecil, Version=0.11.4.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[DEBUG @ 10:48:07 | IPA/LibraryLoader] Looking for file Mono.Cecil.dll
[DEBUG @ 10:48:07 | IPA/LibraryLoader] Found file Mono.Cecil.dll as C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Libs\Mono.Cecil.dll
[DEBUG @ 10:48:07 | IPA] Configuring exit handlers
[DEBUG @ 10:48:07 | IPA/Injector] Prepping bootstrapper
[DEBUG @ 10:48:07 | IPA/Injector] Finding backup
[DEBUG @ 10:48:07 | IPA/Injector] Ensuring patch on UnityEngine.CoreModule exists
[DEBUG @ 10:48:07 | IPA/Config] Generated impl WriteTo IPA.Loader.DisabledConfig<Generated>
[DEBUG @ 10:48:07 | IPA/LibraryLoader] Resolving library Mono.Cecil, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[DEBUG @ 10:48:07 | IPA/LibraryLoader] Looking for file Mono.Cecil.dll
[DEBUG @ 10:48:07 | IPA/LibraryLoader] Found file Mono.Cecil.dll as C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Libs\Mono.Cecil.dll
[INFO @ 10:48:07 | _] System.IO.IOException: Win32 IO returned 1224. Path: C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\Managed\UnityEngine.CoreModule.dll
[INFO @ 10:48:07 | _]   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <eae584ce26bc40229c1b1aa476bfa589>:0 
[INFO @ 10:48:07 | _]   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
[INFO @ 10:48:07 | _]   at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
[INFO @ 10:48:07 | _]   at Mono.Cecil.ModuleDefinition.GetFileStream (System.String fileName, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00006] in <3a0e7329a9804533b861537920fb084e>:0 
[INFO @ 10:48:07 | _]   at Mono.Cecil.ModuleDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters) [0x00006] in <3a0e7329a9804533b861537920fb084e>:0 
[INFO @ 10:48:07 | _]   at Mono.Cecil.AssemblyDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters) [0x00000] in <3a0e7329a9804533b861537920fb084e>:0 
[INFO @ 10:48:07 | _]   at Mono.Cecil.AssemblyDefinition.Write (System.String fileName) [0x00007] in <3a0e7329a9804533b861537920fb084e>:0 
[INFO @ 10:48:07 | _]   at IPA.Injector.Injector.InstallBootstrapPatch () [0x0035b] in <bff3e39a56ea4c78b6adde973f9902ec>:0 
[INFO @ 10:48:07 | _]   at IPA.Injector.Injector.Main (System.String[] args) [0x0007b] in <bff3e39a56ea4c78b6adde973f9902ec>:0 
<pre>
</details>

**Comment by Melopod** [comment]
Uninstall and reinstall BSIPA via the "Uninstall BSIPA" in the settings tab. For further help please refer either to the bsmg.wiki or join the BSMG discord server at discord.gg/beatsabermods and access the pc-help channel, as this is a mod related issue, not an MA issue in particular.

**Comment by hell1337hound** [comment]
same here

**Comment by Melopod** [comment]
Please refer to the comment above yours

**Comment by pravic** [comment]
Ditto.

Uninstall BSIPA didn't work - the game was not able to start afterwards at all, it just started and immediately closed.

"Validate integrity of game files" did help - it redownloaded 7 files. Afterwards, the game was fine, and I was able to install mods.

**Comment by SashapounNako** [comment]
I launched IPA manually, re-downloaded in ModAssisstant mods and re-launched IPA, and it seems to work well for me. Maybe a bug from IPA ?
