### ISSUE TITLE
Mod Assistant Startup Bug

### ISSUE THREAD

**Issue by BeatSaberKid123** [bsmg/ModAssistant#460]
All I did was download and start up the app and this appeared
![Screenshot 2022-04-29 212731](https://user-images.githubusercontent.com/104660939/166085035-78de8969-ae1a-4ec7-999b-9c951f4e1e5d.jpg)
I clicked ok to try to fix the issue but I'm not sure what to do when this pops u
![Screenshot 2022-04-29 213023](https://user-images.githubusercontent.com/104660939/166085120-7585b506-9fd8-4f06-adb3-df1c8d96f27e.jpg)
I tried hitting save on right away, while in a folder, and a few other ways but I still couldn't get Mod Assistant to run

**Comment by Assistant** [comment]
You have to be inside the Beat Saber folder, try navigating down inside it, and then clicking Save.

**Comment by ModdingPink** [comment]
Stale
