### ISSUE TITLE
Unable to download anything from bsaber

### ISSUE THREAD

**Issue by hqnna** [bsmg/ModAssistant#467]
Every time i try to save playlists or songs I get this error:
![image](https://user-images.githubusercontent.com/46457601/176730220-7718c942-a1b0-42c4-af08-2a2a24acc564.png)

**Comment by gerardmassey** [comment]
I'm also having this issue.

**Comment by Dylan-Brotherston** [comment]
I also get the same error message when using one-click install for playlists.
one-click install for individual songs still works.

**Comment by Warpeas** [comment]
Having the same issue.

**Comment by Tartaroko** [comment]
same

**Comment by XepherTim** [comment]
Same issue with playlists, however I did not have the issue when downloading a playlist from beatsaver.com, so maybe it's a website issue?

**Comment by Dylan-Brotherston** [comment]
It appears that this was indeed an issue with the saber site.
I can now download playlists as normal.

**Comment by Dylan-Brotherston** [comment]
wait, there was an update bcfd56af98c6c768187829e652d45dc82872eb57 and I didn't even notice
