### ISSUE TITLE
Noodle existions not showing up

### ISSUE THREAD

**Issue by aidenpro55** [bsmg/ModAssistant#477]
It was werid its not showing up even when i search it.

**Comment by aidenpro55** [comment]
K thanks!

**Comment by dluhhbiu** [comment]
@Melopod how to realise which version beat saber the noodle extension is supporting? I tried 1.24 and it did not work(

**Comment by Mizamook** [comment]
Please, I'd love to know which is the latest version supporting Noodle Extensions ... life is so bland wihtout noodles.

**Comment by d-uzlov** [comment]
Noodle was updated for 1.25 a week ago but it seems like the list of mods hasn't been updated for a long time.

You can install it manually from `Aeroluna/Heck` repo, just don't forget to install dependencies.

**Comment by Melopod** [comment]
Mod Assistant pulls mods from BeatMods. They have to be approved for a game version for them to show up, there is no specific list of mods created just for this purpose.
I believe Noodle Extensions has in fact been updated, yes, but it has not been approved yet on BeatMods and is therefore not appearing on ModAssistant. You can either wait for it to be or download and install the mod manually from the repo, as the above commenter suggests.

**Comment by rk-exxec** [comment]
> You can install it manually from Aeroluna/Heck repo, just don't forget to install dependencies.

It doesnt mention any deps. Or do I just install Heck, Chroma and Noodle?

**Comment by d-uzlov** [comment]
> It doesnt mention any deps. Or do I just install Heck, Chroma and Noodle?

You can check the logs (in the `Beat Saber/Logs/` folder) to finds out which dependencies you are missing.
I had to also install LookupID lib for Chroma.
I don't know if there are other dependencies because I already had a bunch of mods installed.
