### ISSUE TITLE
Erroneous mod version mapping BS 1.24.1 => _Heck 1.4.5

### ISSUE THREAD

**Issue by ribcakes** [bsmg/ModAssistant#480]
I'm pretty new to beat saber modding so I don't know if this is the correct place to file an issue.

I have used the Beat Saber Legacy Launcher to install v 1.24.1 and when trying to install some mods like Chroma or Noodle Extensions, the ModAssistant application automatically selects _Heck to be installed as well as a dependency. This dependency behavior is good and correct, however, the version of _Heck it selects to install, v1.4.5, is incorrect. This causes errors during loading & prevents any custom songs from being started. This was reported [here](https://github.com/Aeroluna/Heck/issues/72) as an issue against the library where the author responded that _Heck v1.4.5 is for BS 1.25.0.

This appears to extend further as the version for NoodleExtensions ( v1.5.4 ) the assistant attempts to install for BS v1.24.1 also specifies [that it is for BS v1.25.0](https://github.com/Aeroluna/Heck/blob/master/NoodleExtensions/manifest.json#L5)

**Comment by Fatalution** [comment]
Considering that this indeed is a bug with ModAssistant, you can grab the old builds of Heck, Chroma and NE from the Heck's GitHub repo in the meantime ;)

**Comment by Kevga** [comment]
ModAssistant just shows what is available on beatmods.com, so this is not a bug. It was an intentional decision to not create a new version on BeatMods for this update. 1.21 - 1.25 are treated as the same and can't receive different versions of mods.

It also most likely won't happen again for future versions of the game.

**Comment by Fatalution** [comment]
Oh I see. Then definitely grabbing the builds for older version from Heck's repo is the only option
