### ISSUE TITLE
mods not working

### ISSUE THREAD

**Issue by cookmydog** [bsmg/ModAssistant#485]
Im assuming beat saber just updated but, the mods aren't working. How often is the program updated?

**Comment by Melopod** [comment]
The ModAssistant versions are unrelated to mod availability. MA just pulls mods from BeatMods and displays them for easy install. If you are having issues with your mods, please refer instead to the troubleshooting guide on the wiki at bsmg.wiki , or ask in the support channels in discord.gg/beatsabermods .

**Comment by LJGamingTVYT** [comment]
Run the game once on the new update. Then, reinstall your mods using an installer linked in the [beginner's guide](https://bsmg.wiki/beginners-guide), such as Mod Assistant.
