### ISSUE TITLE
Integrate BS Steam Version Pull in ModAssistant

### ISSUE THREAD

**Issue by kristoferen** [bsmg/ModAssistant#497]
It would be great if there was a ModAssistant-native feature that made it easy to pull a specific version of BeatSaber from Steam.

**Comment by KiwiHuman** [comment]
I think [BSMannager](https://github.com/Zagrios/bs-manager) or [BeatSaber Legacy Launcher](https://github.com/RiskiVR/BSLegacyLauncher) is what you are looking for

**Comment by ModdingPink** [comment]
Currently outside of the scope of ModAssistant, please use Steams Beta branches or [BSManager](https://github.com/Zagrios/bs-manager)
