### ISSUE TITLE
Custom Sabers not appearing

### ISSUE THREAD

**Issue by AnExistingBeing** [bsmg/ModAssistant#500]
Not sure if this is due to the new update or if its an issue on my end and I'm new to using mod assistant so I figured I'd say something here. Any new custom sabers I install from ModelSaber don't show up in game even though mod assistant says they're installed and there is no more Custom Sabers page in the menu. Is this just due to the new update breaking things or did I not install something important?

**Comment by Melopod** [comment]
First double-check that the sabers you intend to install are properly installing to your CustomSabers folder in your main game folder. If it is, you may not have installed a mod that handles custom sabers, such as SaberTailor or Naluluna's Custom Sabers mod. If you have both installed, check with those mods or ask for support in the Beat Saber Modding Group discord.gg/beatsabermods.
If the sabers are _not_ installing properly in the first place, it is an MA or ModelSaber problem. If not, MA is not your issue, just to help narrow things down!
