### ISSUE TITLE
Update pls

### ISSUE THREAD

**Issue by NatsuFT347** [bsmg/ModAssistant#505]
Can we please have updates to ModAssistant?
It's been two versions now, that we haven't been able to use up-to-date Mods
<3

**Comment by Melopod** [comment]
This recent version update includes a new Unity version update that requires a lot of work for mods to be maintained. If you would like to use a previous version's mods, you can downgrade temporarily to a previous version of the game via the beta channels on Steam or Quest, or more permanently with downgrading tools.

That being said, here's a couple points about how it all works:

- Mod Assistant is only a tool that provides easy installation of mods, compiled on BeatMods. MA itself has nothing to do with which mods are available or not, it just lists them when approved. It does not require any updates when the game does.

- Mods not being available when a game update releases is normal! While some mods may work with new versions as the code they're based on doesn't change, most of the time mods rely on code that changes, and therefore need to be updated themselves. Please be patient as modders are volunteering their time to maintain these mods, and it may take some time for things to be updated again.

Hope that clears things up! If you need any more help, please join the Beat Saber Modding Group at discord.gg/beatsabermods
