### ISSUE TITLE
Nothing is showing up 💀 

### ISSUE THREAD

**Issue by maxboyee** [bsmg/ModAssistant#506]
Yo. I just got Beat Saber on steam yesterday and immediately went to mod it. I've watched multiple vids, looked through the issues page on here, etc, just to be sure. I've got everything downloaded, I had to downgrade my game version because there weren't any mods for the newest update. Everything says it's fine, but nothing is popping up on Beat Saber. I reinstalled it, tried to update it, but nothing is working. I'd really appreciate some help lol, thanks.

**Comment by alirobe** [comment]
A new version just came up and broke all mods, seems to be a work-around here: https://www.reddit.com/r/beatsaber/comments/13qzlvj/beat_saber_1300_released_featuring_the_queen/

**Comment by scaidermern** [comment]
Revert back to version Beat Saber 1.29.1, see https://github.com/Assistant/ModAssistant/issues/504#issuecomment-1547750865
