### ISSUE TITLE
Been 3 weeks, going on 4, any updates from the Mod authors?

### ISSUE THREAD

**Issue by ZaberModder** [bsmg/ModAssistant#510]
Just wondering, since it's soon to be 4 weeks since  1.30 came out, just checking to see if our esteemed mod developers have had a chance to adjust the mods for 1.30?

Much appreciate it!

**Comment by scaidermern** [comment]
Revert back to version Beat Saber 1.29.1, see https://github.com/Assistant/ModAssistant/issues/504#issuecomment-1547750865

**Comment by ZaberModder** [comment]
naw, I play online too, and online doesnt work with previous versions. It's been a month, what's the hold up??

**Comment by jabberjabberjabber** [comment]
These servers beg to differ:

* https://bssb.app/master-servers

There are guides online on how to revert your install so you can play online. Stop bothering the people who do all the hard work to get it running for you.

**Comment by wolfey2900** [comment]
this works on showing the mods but sadly on my end beat saber flat out crashes on launch now.
