### ISSUE TITLE
Mod assistant

### ISSUE THREAD

**Issue by Upstage153** [bsmg/ModAssistant#511]
Okay so when i've downloaded mod assistant im not sure if im doing anything wrong but i have no mods on mod assistant at all on the newest beat saber upgrade 1.31.0

**Comment by Melopod** [comment]
Welcome to Beat Saber Modding!

Appreciate your enthusiasm, but just to clarify a couple things:

- Mod Assistant is only a tool that provides easy installation of mods, compiled on BeatMods. MA itself has nothing to do with which mods are available or not, it just lists them when approved.
- Mods not being available when a game update releases is normal! While some mods may work with new versions as the code they're based on doesn't change, most of the time mods rely on code that changes, and therefore need to be updated themselves. Please be patient as modders are volunteering their time to maintain these mods, and it may take some time for things to be updated again.
Hope that clears things up! If you need any more help, please join the Beat Saber Modding Group at discord.gg/beatsabermods
