### ISSUE TITLE
1.29.1 add since on Steam is now available through beta and don't need playing with the manifest ID

### ISSUE THREAD

**Issue by Lefthornet** [bsmg/ModAssistant#519]
Sorry if maybe someone already asked for this, I searched through the issues and didn't find this request. But adding version 1.29.1 will be great to allow more people to access easily the mods (on the app I only see 1.29.0 and 1.29.4) since Steam now allows to select that version as " legacy" from the Beta participation section on properties. I personally just update the manifest ID and have the automatic update disabled, but for a lot of people that could help to get into mods more easily. Thanks, have a good day.
![Mod Assistant version pick](https://github.com/Assistant/ModAssistant/assets/56377042/75a42b07-6590-4edb-b439-928c09632d85)

![Beat saber 1 29 1 option](https://github.com/Assistant/ModAssistant/assets/56377042/a3cfaad0-c472-46fd-8d6b-43bb2bd3ba84)

**Comment by golddragon007** [comment]
Hello, you see only those as those are available on beatmods. The cherry on the cake is that 1.29.4 has no mods, and 1.29.0 has mods, but most likely none of them will be compatible with 1.29.1

**Comment by DeadlyKitten** [comment]
The versions list is pulled from BeatMods.
