### ISSUE TITLE
Versionsliste konnte nicht geladen werden, Mods Tab Deaktiviert.

### ISSUE THREAD

**Issue by jedoschmidt** [bsmg/ModAssistant#522]
Versionsliste konnte nicht geladen werden, Mods Tab Deaktiviert.
Bitte Programm neu starten um es nochmal zu versuchen.

![image](https://github.com/Assistant/ModAssistant/assets/69874114/cb4aeec6-e870-4084-bd36-6f4021c3924e)

![image](https://github.com/Assistant/ModAssistant/assets/69874114/fa720b10-135f-41f1-841a-23a3fe13f113)

[2023.07.25.12.04.18.log](https://github.com/Assistant/ModAssistant/files/13259701/2023.07.25.12.04.18.log)

**Comment by AndiMajore** [comment]
Gleiches Problem hier! Denke irgend eine online Resource ist temporär offline, da es auch mit meinen Backups von alten BS Versionen nicht klappt.
