### ISSUE TITLE
mod assistant update when?

### ISSUE THREAD

**Issue by TtvShadowAngel** [bsmg/ModAssistant#527]
i would just really like to know when the next update will come out. 

thanks

**Comment by Assistant** [comment]
There might be an update when a replacement for BeatMods comes along to interface with the new API if necessary.
Otherwise probably never, I consider Mod Assistant to be complete.

**Comment by TtvShadowAngel** [comment]
ok i just think that if you do get an update there should be more mods for
1.34.2 (beta) but that's just an idea and i have no knowledge of how to
make mods so i don't know if it's hard to make mods for a beta or not but i
do think that more 1.34.2 beta mods would be nice

thanks for letting me know.
Ttv Shadow Angel

**Comment by Melopod** [comment]
While Assistant did answer your question, I think you may still be a bit confused as to how this all works.

- Mod Assistant is only a tool that provides easy installation of mods, compiled on BeatMods. MA itself has nothing to do with which mods are available or not, it just lists them when approved. **It does not require any updates when the game does.**

- Mods not being available when a game update releases is normal! While some mods may work with new versions as the code they're based on doesn't change, most of the time mods rely on code that changes, and therefore need to be updated themselves. Please be patient as modders are volunteering their time to maintain these mods, and it may take some time for things to be updated again.

- Should be self-explanatory from the other 2 points, but, Mod Assistant maintainers are _not_ the same people as the mod maintainers. You can wish for more mods here all you like, but you're asking the wrong people.

Hope that clears things up! If you need any more help, please join the Beat Saber Modding Group at discord.gg/beatsabermods
