### ISSUE TITLE
Unable to select beat saber version

### ISSUE THREAD

**Issue by Gamer101233** [bsmg/ModAssistant#528]
When i go to open the mod assistant and i want to select the game version it is greyed out and wont let me select the game version i want to go to.

**Comment by MrKingfisher** [comment]
@Gamer101233  this actually affected all mod managers. i had a bit today but then it solved it self as if some service was down that mood assistant and all others was pending on

**Comment by Gamer101233** [comment]
Issue still is there i cant select any game versions @MrKingfisher

**Comment by Gamer101233** [comment]
im woundering if all servicers if any that control that were fullt shut down due to something.

**Comment by Melopod** [comment]
MA does not typically allow you to select a game version, as it automatically detects the game version you have installed and displays the corresponding mod versions that work with that particular game version. 
In case there was any confusion about this, selecting another game version in MA _does not_ change your installed game version, that's not how that works.

**Comment by DeadlyKitten** [comment]
Version detection was fixed in #547
