### ISSUE TITLE
Program won't work unless recompiled with isVoid() set True.

### ISSUE THREAD

**Issue by V-Rixxo** [bsmg/ModAssistant#531]
Under Classes / Utils.CS a function called "IsVoid()" will prevent the application from working with a target directory if it's unofficial. 

Just trying to verify if this behavior is on purpose or not. This issue doesn't affect me but I noticed it in the code.

**Comment by sofi3066389963** [comment]
The program won't function correctly unless it's recompiled with the [isVoid flag enabled](https://lightrome.com/). Make sure to adjust your compilation settings accordingly.

**Comment by DeadlyKitten** [comment]
This is working as intended.
