### ISSUE TITLE
Having an issue with the Model Downloader not loading anything

### ISSUE THREAD

**Issue by DeHavain** [bsmg/ModAssistant#539]
_This issue was also posted on the Model Downloader page..._

Right now I have no way of downloading any new models, sabers, or other models from within the game, and nothing I've tried has worked.
I mainly used Mod Assistant to download my mods and haven't had an issue until maybe a year ago.
I can still drag and drop the models I had saved on my computer before and use the models I already have but nothing new can be downloaded.

I've already reinstalled blank versions of both the mod assistant and beat saber to try and fix it but no luck.
the More Models tab does show up but nothing loads and searching or sorting anything in the window sticks it in an infinite load of "1 of 1" pages.

_I'm really scratching my head here._

I also have an issue with the local scoreboard mod not tracking any of my plays other than when I pass the level. ( but this is more secondary and less important)

I'm running ver. 1.29.0 of Beat Saber right now with ver. 1.1.33 of mod assistant. I've checked that I'm installing the right mods for my version of Beat Sabers.

**Comment by Melopod** [comment]
Heya

Any issues with mods need to be reported to and handled by the mod maintainers. MA is just an installer, it has zero input on what mods do or if they bug, it just checks if there's a mod and then installs in.

To that same point, the version of MA doesn't mean anything, it's pretty minimal function and therefore is pretty much at its final version, and available mods have nothing to do with the version of MA, if that makes sense.

It looks like you've already reported this to Model Downloader, which was the right thing to do! But it doesn't sound like any of your issues are related to MA at all. I would also suggest reporting the scoreboard issue to that particular mod, not here.

Hope this clears things up and best of luck with your mods!

**Comment by DeHavain** [comment]
Thanks!
I had a feeling that is what I had to do so I posted there first but I wasn't entirely sure. I just wanted to give as much info as i could if that helped since I'm new to modding as a whole.
