### ISSUE TITLE
Mods not working at all on 1.37.3

### ISSUE THREAD

**Issue by MusicMadness27** [bsmg/ModAssistant#543]
ever since the update from 1.37.3 the mods are not working anymore, beatleader won't show,i can still play my downloaded songs but that's it. weird thing is every time after i start the game and i verify the integrity on steam it finds 1 problem. I fix the problem, restart the game, still nothing works and again have that integrity problem. i also tried reinstalling the game and all the mods but still nothing works

**Comment by ModdingPink** [comment]
This is not an issue with MA, please reach out to the Beat Saber Modding Group Discord if you need help with anything <3
https://discord.gg/beatsabermods
