### ISSUE TITLE
BeatSaber Will Not Open With Mods Installed

### ISSUE THREAD

**Issue by DaniTrae** [bsmg/ModAssistant#546]
Used to have Mod Assistant with Beatsaber before, I had to wipe my computer so I lost everything. I didn't do anything fancy, just wanted custom maps. Now, if I have the game installed, it works fine. However, once I install the basic mods it recommends, it refuses to load up. Nothing but a black screen. So I go into Mod Assistant, I hit Uninstall All Mods, and the game works perfectly. 

I'm not tech savvy, especially when it comes to mods. This is the only thing I've ever been able to work properly. I really am not good at modding things. Any advice would be awesome.

**Comment by Lightzzzv** [comment]
Same issue man.

**Comment by hurleyp123** [comment]
Experiencing same issue with Oculus Rift. Tried to restart steam, restarted Oculus/Meta app, fully reinstalled BeatSaber. Won't launch with any mods installed even if its just the baseline mods. I get the splash screen and then goes black and does not start.

**Comment by ModdingPink** [comment]
This may be issues with the version detection for MA which is awaiting a release, please reach out to the Beat Saber Modding Group Discord if you need help with anything <3
https://discord.gg/beatsabermods
