### ISSUE TITLE
What happened to release v1.1.34?

### ISSUE THREAD

**Issue by amarevite** [bsmg/ModAssistant#549]
The tag `v1.1.34` previously had a release with `ModAssistant.exe` attached. That release is no longer available and `v1.1.33` is now the latest release. What happened to `v1.1.34`?

**Comment by ModdingPink** [comment]
Community Pushback mainly, we're looking into options soon

**Comment by Kakifrucht** [comment]
+1 to keep it running, especially if you already patched it. i vastly prefer it over BSManager, which is generally slow to load, offers a bunch of features i don't care about and doesn't mod the game any better than MA did. i understand that some people might prefer if everyone used the same manager to make supporting easier, but that would only make sense if it actually was an upgrade. it isn't right now and i don't care about any of the extra features it offers. MA is robust and always worked great for me. fast, snappy, functional.
