### ISSUE TITLE
Switch between steam and oculus game type

### ISSUE THREAD

**Issue by Meatex** [bsmg/ModAssistant#61]
I found the launcher command line to run steam with oculus API after I added mods and now mods don't load. 
I assume because I am a dumb dumb and set it to steam type so its got the steam mods and now im running it as native oculus.
I tried uninstalling mods to see if I could get the first time prompt again but no joy
Tried looking through registry and didn't find anything but not sure what im looking for.

**Comment by Parapass** [comment]
Run the game first after setting the oculus API launch parameter.
