### ISSUE TITLE
PlayerData integrity checking.

### ISSUE THREAD

**Issue by cedws** [bsmg/ModAssistant#9]
Thanks for this great tool.

I had a bit of trouble getting mods working earlier; some panels in the game were missing, preventing me from playing (but the game worked fine un-modded). It seemed to be caused by my `PlayerData.dat` in `LocalLow/Hyperbolic Magnetism/Beat Saber` becoming corrupt. As soon as I created a fresh `Beat Saber` folder, everything started working again.

Would it be possible for the mod installer to do some kind of checks in the `PlayerData.dat` file to make sure it won't cause issues when playing? Unfortunately, I don't know specifically what in the file the game was complaining about.

**Comment by ModdingPink** [comment]
Stale and would require changes between old and new version due to them moving to ini
